#!/bin/bash

FPKGDIR="/usr/local/fpkg" # where all packages are located at
EDITOR="vim"              # change this to your preferred editor

# logging stuff, leave them commented out
# to keep disabled
#FPKG_LOG="/tmp/fpkg_log" # log directory, /tmp makes sense to me
#LOG_FMT="%Y%m%d-%H%M%S"  # the format used to timestamp the log files
                          # see man page of date for more

# to restore the terminal state and quit with a code
quit () {
	popd > /dev/null # restore user's working directory quietly
	stty echo        # unhide their keystrokes
	exit $1          # exit with a given code
}

# to display an error and also quit with non-zero
error () { 
	echo "ERROR: $1" # use argument as the error message
	quit 1           # exit with error
}

# to check if a package exists
exist_check () {
	if [[ -z $1 ]]; then
		error "package name was not provided!"
	fi

	grep -w $1 pkg.list > /dev/null 2>&1 # running this just to get its return value
	if [[ $? > 0 ]]; then
		error "$1 not found in pkg.list! Was it a typo?"
	fi
}

# to check if elevated privileges are needed
write_check () {
	# get return code to see if we can write to any of the files
	touch $FPKGDIR > /dev/null 2>&1
	ret=$((ret + $?))
	touch $FPKGDIR/pkg.list > /dev/null 2>&1
	ret=$((ret + $?))
	touch $FPKGDIR/ii > /dev/null 2>&1
	ret=$((ret + $?))

	# if any of the touch's fail
	if [[ $ret > 0 ]]; then 
		error "you cannot write to $FPKGDIR! Please run as root!"
	fi
}

# to perform an update
update () {
	# not sure if that's a good implementation
	# of it
	git pull --recurse-submodules=on-demand --rebase
	# and then move to the previous dir
	cd - > /dev/null
}

# check if $FPKGDIR exists in the first place
# else perform an initial setup
if [[ ! -d $FPKGDIR ]]; then
	stty echo
	echo "ERROR: $FPKGDIR does not exist! Create it now? [Y/n]"
	read choice

	if [[ $choice != "n" ]]; then # so that the default is "yes"
		mkdir -pv $FPKGDIR/ii     # create the ii one too already
		cp .bashrc $FPKGDIR       # and copy .bashrc to the main dir 
	fi

	quit 1
fi

# environment setup
stty -echo          # hide keystrokes, note that they still get registered
pushd . > /dev/null # save user's current directory
cd $FPKGDIR         # so that we can go to $FPKGDIR

case $1 in
	# refresh the packages with `git pull'
	"update" | "u")
		# no extra arguments? then all packages will be checked
		if [[ -z $2 ]]; then
			entries=$(cat pkg.list | wc -l) # how many packages do we have?

			for ((i = 1; i <= $entries; i++)); do
				pkg_dir=$(head -n $i pkg.list | tail -1)
				cd $pkg_dir > /dev/null 2>&1
					
				if [[ $? != 0 ]]; then
					error "$pkg_dir does not exist! Remove its entry
				    	   with 'fpkg delete' and try again. Aborting..."
				fi

				echo "$pkg_dir:"
				update $pkg_dir
			done
		# refreshing just a single package?
		else
			exist_check $2 # check if it exists first
			cd $2		   # change to its directory if so
			update $2	   # and perform the update
		fi
	;;

	# requested the installation of a package?
	"install" | "i")
		exist_check $2
		write_check

		cd $2

		if [[ $FPKG_LOG && $LOG_FMT ]]; then
			# check if the log dir exists first
			# as it's by default inside /tmp
			if [[ ! -d $FPKG_LOG ]]; then
				mkdir $FPKG_LOG
			fi

			# $LOG_FMT gets expanded here for creating the file
			LOGFILE=$FPKG_LOG/$(printf "$2-%($LOG_FMT)T")

			$FPKGDIR/ii/$2.ii install | tee -a $LOGFILE

			# warn the user about it
			echo -e \\n"Build log saved to $LOGFILE."
		else
			$FPKGDIR/ii/$2.ii install
		fi
	;;

	# requested the uninstallation of a package?
	"remove" | "r")
		exist_check $2
		write_check

		cd $2

		$FPKGDIR/ii/$2.ii remove
	;;

	# requested the list of registered packages?
	"list" | "l")
		cat pkg.list

		echo -e \\n"Total: $(cat pkg.list | wc -l)" # see how many packages we have too
	;;

	# adding an entry to the list?
	"add" | "a")
		write_check

		# and check if we even have a package name
		if [[ -z $1 ]]; then
			error "package name was not provided!"
		fi

		# make keystrokes visible again
		stty echo
		
		# add the package to the list
		echo $2 >> pkg.list

		# write a template for it to make it easier for the user
		# i couldn't get this to work by using a single call to
		# echo so i came up with this
		echo    "# - Installation instructions for package $2 -" >  ii/$2.ii
		echo    "# Inside install (), write the commands for"    >> ii/$2.ii
		echo    "# installing the package,"                      >> ii/$2.ii
		echo    "# and inside remove (), write the commands for" >> ii/$2.ii
		echo -e "# uninstalling it too."\\n\\n                   >> ii/$2.ii
		
		# write a commented out privilege check section so that if
		# there're any steps requiring elevated privileges a check
		# is made for it
		echo -e "#if [[ \$(id -u) != 0 ]]; then"					 >> ii/$2.ii
		echo -e "#\\techo \"This action requires root privileges!\"" >> ii/$2.ii
		echo -e "#\\texit 1"                                         >> ii/$2.ii
		echo -e "#fi"\\n                                             >> ii/$2.ii

		echo -e "install () {"\\n\\n"}"\\n >> ii/$2.ii
		echo -e "remove () {"\\n\\n"}"\\n  >> ii/$2.ii

		# this is necessary for being able to call one of the functions when needed
		echo "# DO NOT REMOVE! This is used for calling the" >> ii/$2.ii
		echo "# functions from this ii..."                   >> ii/$2.ii
		echo "call=\$1; \$call"                              >> ii/$2.ii

		# open up the text editor so that the user can write on
		# that template
		$EDITOR ii/$2.ii

		# finally, make it executable so that fpkg can run it
		chmod +x ii/$2.ii
	;;

	# just checking an .ii?
	"peek" | "p")
		exist_check $2

		cat ii/$2.ii
	;;

	# going to the package's directory?
	"goto" | "g")
		exist_check $2

		# see if we even have the .bashrc to begin with
		if [[ ! -r $FPKGDIR/.bashrc ]]; then
			error "your \$FPKGDIR doesn't have an existing or readable .bashrc!"
		fi

		stty echo

		export FPKGDIR    # those are necessary to make it able to start the
		export PKG_DIR=$2 # shell at the desired directory

		sh -c 'cd $FPKGDIR/$PKG_DIR;                    # change to the directory
		       echo "Working on $PKG_DIR/, ^D to exit"; # make the user aware of it
		       exec bash --rcfile $FPKGDIR/.bashrc'     # and here it goes
	;;

	# editing a package's .ii?
	"edit" | "e")
		exist_check $2
		write_check

		stty echo

		$EDITOR ii/$2.ii
	;;

	# delete an entry from the list?
	"delete" | "d")
		exist_check $2
		write_check

		stty echo
		entry=$(grep -w "^$2" pkg.list -n | awk -F: '{ print $1 }') # get index number of package
		sed -i "$entry"d pkg.list # and delete the package using it
		rm ii/$2.ii
		echo "$2 removed from pkg.list, would you like to remove its files as well? [y/N]"
		read choice

		if [[ $choice = 'y' ]]; then # same thing but default'ing to "no"
			rm -rf $2
			if [[ $? = 0 ]]; then
				echo "Done"
			fi
		fi
	;;

	# requested the message of last git commit?
	"message" | "m")
		if [[ $2 = "-d" ]]; then
			shift
		fi

		exist_check $2
		cd $2

		# and its diff?
		if [[ $1 = "-d" ]]; then
			git show
		else
			git --no-pager log -1 --pretty="Who: %cn%nWhat: %s%nDetails: %b"
		fi
	;;

	# requested the commit history?
	"history" | "H")
		# regular expression to check if argument
		# is a number
		number_check="^[0-9]+$"

		# shift if it is
		if [[ $2 =~ $number_check ]]; then
			shift
		fi

		exist_check $2
		cd $2

		# and change the depth to that
		if [[ $1 =~ $number_check ]]; then
			DEPTH=$1
		else # or not
			DEPTH=5
		fi

		git --no-pager log -$DEPTH --pretty="(%cd)%nWho: %cn%nWhat: %s%n%b"
	;;

	# requested the version?
	"version" | "v")
		echo "fpkg, version 3.0.0-beta3."
		echo "Written by ruby R53 (https://github.com/ruby-R53) on July 2024"
	;;

	# didn't even input a valid action or wants to know
	# them?
	"help" | "h" | *)
		echo "Usage: $0 <action> [package]"
		echo "Actions (and their short forms):"
		echo "(h)elp               - shows this help message"
		echo "(u)pdate [pkg]       - git pull every package listed in pkg.list, you"
		echo "                       can optionally update only [pkg] as well"
		echo "(i)nstall <pkg>      - install <pkg> using \$FPKGDIR/ii/<pkg>.ii"
		echo "(r)emove <pkg>       - uninstall <pkg> using \$FPKGDIR/ii/<pkg>.ii also"
		echo "(l)ist               - list registered packages"
		echo "(a)dd <pkg>          - register <pkg>"
		echo "(p)eek <pkg>         - take a peek at <pkg>'s .ii"
		echo "(g)oto <pkg>         - go to <pkg>'s directory"
		echo "(e)dit <pkg>         - edit <pkg>'s ii file"
		echo "(d)elete <pkg>       - remove <pkg> from pkg.list"
		echo "(m)essage [-d] <pkg> - get comment from last commit of <pkg>. Takes an"
		echo "                       optional -d for getting its diff"
		echo "(H)istory [n] <pkg>  - get <pkg>'s commit history. Takes an optional"
		echo "                       [n] to get a custom depth. Defaults to 5"
		echo "(v)ersion            - get fpkg's version"

		# exit with error if input wasn't
		# for the help text
		if [[ $1 != "help" ]]; then
			quit 1
		fi
	;;
esac

# and the program is done!
quit 0
